name: BanditScan

on:
  pull_request:
  workflow_dispatch:

jobs:
  bandit-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      id: bandit_scan
      run: bandit -r . -f json -o bandit_results.json
      continue-on-error: true

    - name: Check Bandit Results
      id: check_results
      run: |
        critical_vulns=$(jq '.metrics.TOTAL.CRITICAL' bandit_results.json)
        if [ "$critical_vulns" -gt 0 ]; then
          echo "Block"
          echo "comment=Block" >> $GITHUB_ENV
          exit 1
        else
          echo "Successful"
          echo "comment=Successful" >> $GITHUB_ENV
        fi

    - name: Add PR Comment
      uses: actions/github-script@v6
      with:
        script: |
          const comment = process.env.comment;
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.pull_request.number,
            body: comment,
          });

    - name: Merge PR
      if: success()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          });
